### ISSUE TITLE
configuration.output.filename: A relative path is expected

### ISSUE THREAD

**Issue by classikd** [itzikbenh/WordPack#1]
Hello,

I had to set the output path as below to make the building task works:
`
filename: 'js/[name].js',
`

![error-wp](https://user-images.githubusercontent.com/5224312/41813324-14c3b4b0-7734-11e8-9434-0389ec398a67.JPG)

Thanks for this repo by the way, I've discovered you yesterday on youtube, just tried it now and it works like a charm.
By the way if you discovered great new features since the past year which could be added to this repo i'd be happy to know them :-D

Au revoir ! 😎🎂

**Comment by itzikbenh** [comment]
Glad it helped you. Weird, never had that issue, probably it's because the way your folders are structured. 
Well, there's Webpack 4, but apparently Webpack does all it can to complicate things, so I'm avoiding it for the mean time, I just stick to what works for the moment.
